# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
# no need to update frequently
  schedule:     
    - cron: "0 0 * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:    
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 21
          plugin_habits_from: 500
          config_timezone: America/Los_Angeles
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_introduction: yes
          plugin_introduction_title: yes
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
       
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.devto.svg
          token: NOT_NEEDED
          base: ""
          plugin_posts: yes
          plugin_posts_limit: 2
          plugin_posts_source: hashnode
          plugin_posts_user: karanthakur
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: thisiskaransgit
          base: header
          plugin_introduction: yes
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
